import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class GlobalsService {
  listCity = ['An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bạc Liêu',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Định',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Cao Bằng',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Tĩnh',
    'Hải Dương',
    'Hậu Giang',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Long An',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
    'Phú Yên',
    'Cần Thơ',
    'Đà Nẵng',
    'Hải Phòng',
    'Hà Nội',
    'TP Hồ Chí Minh'];
  
  listCitySyntax = 
    ['AG',
    'BRVT',
    'BG',
    'BK',
    'BL',
    'BN',
    'BTR',
    'BDD',
    'BD',
    'BP',
    'BT',
    'CM',
    'CB',
    'DL',
    'DKN',
    'DB',
    'DNai',
    'DT',
    'GL',
    'HG',
    'HN',
    'HT',
    'HD',
    'HG',
    'HB',
    'HY',
    'KH',
    'KG',
    'KT',
    'LC',
    'LD',
    'LS',
    'LC',
    'LA',
    'ND',
    'NA',
    'NB',
    'NT',
    'PT',
    'QB',
    'QN',
    'QNG',
    'QNINH',
    'QT',
    'ST',
    'SL',
    'TN',
    'TB',
    'TN',
    'TH',
    'HUE',
    'TG',
    'TV',
    'TQ',
    'VL',
    'VP',
    'YB',
    'PY',
    'CT',
    'DN',
    'HP',
    'HN',
    'TPHCM'];
  input: number;
  output: string;
  err: string;

  // changeSyntax(input: string) {
  //   this.input = this.listCity.indexOf(input);
  //   if (this.input === -1) {
  //     return this.err = 'Tỉnh thành này hiện không thuộc Việt Nam';
  //   } else {
  //     return this.output = this.listCitySyntax[this.input];
  //   }
  // }
}

